version: '3.8'

services:
  qr-collector:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    restart: unless-stopped
    ports:
      - "5200:5000"
